services:
  discord-backup:
    build: .
    container_name: discord-backup
    env_file:
      - .env
    volumes:
      - ${BACKUP_DIR}:/backup
    command:
      - --token
      - ${BOT_TOKEN}
      - --server-id
      - ${SERVER_ID}
      - --output-path
      - /backup/output
      - --media-path
      - /backup/media
      - --data-file
      - /backup/data.json
    restart: "no"
