services:
  discord-backup:
    image: discord-backup
    container_name: discord-backup
    env_file:
      - .env
    volumes:
      - ${BACKUP_DIR}/output:/output
      - ${BACKUP_DIR}/media:/media
      - ${BACKUP_DIR}/data.json:/data.json
    command:
      - --token
      - ${BOT_TOKEN}
      - --server-id
      - ${SERVER_ID}
      - --output-path
      - /output
      - --media-path
      - /media
      - --data-file
      - /data.json
    restart: "no"
